name: "Build Dictionary"
on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: "Pre Release"
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: python filter.py
      - run: python dict.py
      - run: .\kindlegen.exe dict/dict.opf -c2 -verbose -dont_append_source -locale en
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            *.mobi
            dict/*.mobi
