name: "Build Dictionary (Pre-release)"
on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*-rc*"

jobs:
  build:
    name: "Pre Release"
    runs-on: "windows-latest"
    steps:
      - name: "Clone Repo"
        uses: actions/checkout@v3

      - name: "Install Python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: "Build"
        run: |
          python filter.py
          python dict.py
          python kindlegen.py dict/dict.opf -verbose -dont_append_source -locale en
      
      - name: "Publish"
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: ${{ github.ref_name }}
          files: |
            *.mobi
            dict/*.mobi
