name: "Build Dictionary (Pre-release)"
on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*-rc*"

jobs:
  build:
    name: "Pre Release"
    runs-on: "windows-latest"
    steps:
      - name: "Build"
        uses: actions/checkout@v3
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
        run: python filter.py
        run: python dict.py
        run: python kindlegen.py dict/dict.opf -verbose -dont_append_source -locale en
      
      - name: "Publish"
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: |
            *.mobi
            dict/*.mobi
