name: "Pre-release Build"
on:
  push:
    tags:
      - "v*.*.*-rc*"
  pull_request:
    branches:
      - "main"
      - "dev"

jobs:
  build:
    name: "Build & Release"
    runs-on: "windows-latest"
    steps:
      - name: "Clone Repo"
        uses: actions/checkout@v3

      - run: rustup toolchain install stable --profile minimal
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.0
        with:
          cache-on-failure: "true"
          cache-all-crates: "true"

      - name: "Cargo"
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release --all-features
      
      - name: "Build"
        run: |
          .\kindlegen.exe dict/dict.opf -verbose -dont_append_source -locale en
      
      - name: "Publish"
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          name: "Latest Pre-Release"
          tag_name: ${{ github.ref_name }}
          files: |
            dict/*.mobi

permissions:
  contents: write